// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"main/pkg/types"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDisplay creates a new instance of MockDisplay. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDisplay(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDisplay {
	mock := &MockDisplay{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDisplay is an autogenerated mock type for the Display type
type MockDisplay struct {
	mock.Mock
}

type MockDisplay_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDisplay) EXPECT() *MockDisplay_Expecter {
	return &MockDisplay_Expecter{mock: &_m.Mock}
}

// DebugText provides a mock function for the type MockDisplay
func (_mock *MockDisplay) DebugText(line string) {
	_mock.Called(line)
	return
}

// MockDisplay_DebugText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DebugText'
type MockDisplay_DebugText_Call struct {
	*mock.Call
}

// DebugText is a helper method to define mock.On call
//   - line string
func (_e *MockDisplay_Expecter) DebugText(line interface{}) *MockDisplay_DebugText_Call {
	return &MockDisplay_DebugText_Call{Call: _e.mock.On("DebugText", line)}
}

func (_c *MockDisplay_DebugText_Call) Run(run func(line string)) *MockDisplay_DebugText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDisplay_DebugText_Call) Return() *MockDisplay_DebugText_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDisplay_DebugText_Call) RunAndReturn(run func(line string)) *MockDisplay_DebugText_Call {
	_c.Run(run)
	return _c
}

// SetState provides a mock function for the type MockDisplay
func (_mock *MockDisplay) SetState(state *types.State) {
	_mock.Called(state)
	return
}

// MockDisplay_SetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetState'
type MockDisplay_SetState_Call struct {
	*mock.Call
}

// SetState is a helper method to define mock.On call
//   - state *types.State
func (_e *MockDisplay_Expecter) SetState(state interface{}) *MockDisplay_SetState_Call {
	return &MockDisplay_SetState_Call{Call: _e.mock.On("SetState", state)}
}

func (_c *MockDisplay_SetState_Call) Run(run func(state *types.State)) *MockDisplay_SetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *types.State
		if args[0] != nil {
			arg0 = args[0].(*types.State)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDisplay_SetState_Call) Return() *MockDisplay_SetState_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDisplay_SetState_Call) RunAndReturn(run func(state *types.State)) *MockDisplay_SetState_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockDisplay
func (_mock *MockDisplay) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDisplay_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockDisplay_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockDisplay_Expecter) Start() *MockDisplay_Start_Call {
	return &MockDisplay_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockDisplay_Start_Call) Run(run func()) *MockDisplay_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDisplay_Start_Call) Return(err error) *MockDisplay_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDisplay_Start_Call) RunAndReturn(run func() error) *MockDisplay_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockDisplay
func (_mock *MockDisplay) Stop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDisplay_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockDisplay_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDisplay_Expecter) Stop(ctx interface{}) *MockDisplay_Stop_Call {
	return &MockDisplay_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *MockDisplay_Stop_Call) Run(run func(ctx context.Context)) *MockDisplay_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDisplay_Stop_Call) Return(err error) *MockDisplay_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDisplay_Stop_Call) RunAndReturn(run func(ctx context.Context) error) *MockDisplay_Stop_Call {
	_c.Call.Return(run)
	return _c
}
