// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	types0 "main/pkg/types"
	"time"

	"github.com/brynbellomy/go-utils"
	"github.com/cometbft/cometbft/consensus/types"
	"github.com/cometbft/cometbft/rpc/core/types"
	types1 "github.com/cometbft/cometbft/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFetcher creates a new instance of MockFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFetcher {
	mock := &MockFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFetcher is an autogenerated mock type for the Fetcher type
type MockFetcher struct {
	mock.Mock
}

type MockFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFetcher) EXPECT() *MockFetcher_Expecter {
	return &MockFetcher_Expecter{mock: &_m.Mock}
}

// Block provides a mock function for the type MockFetcher
func (_mock *MockFetcher) Block(height int64) (*coretypes.ResultBlock, error) {
	ret := _mock.Called(height)

	if len(ret) == 0 {
		panic("no return value specified for Block")
	}

	var r0 *coretypes.ResultBlock
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*coretypes.ResultBlock, error)); ok {
		return returnFunc(height)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *coretypes.ResultBlock); ok {
		r0 = returnFunc(height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coretypes.ResultBlock)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(height)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFetcher_Block_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Block'
type MockFetcher_Block_Call struct {
	*mock.Call
}

// Block is a helper method to define mock.On call
//   - height int64
func (_e *MockFetcher_Expecter) Block(height interface{}) *MockFetcher_Block_Call {
	return &MockFetcher_Block_Call{Call: _e.mock.On("Block", height)}
}

func (_c *MockFetcher_Block_Call) Run(run func(height int64)) *MockFetcher_Block_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFetcher_Block_Call) Return(resultBlock *coretypes.ResultBlock, err error) *MockFetcher_Block_Call {
	_c.Call.Return(resultBlock, err)
	return _c
}

func (_c *MockFetcher_Block_Call) RunAndReturn(run func(height int64) (*coretypes.ResultBlock, error)) *MockFetcher_Block_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockFetcher
func (_mock *MockFetcher) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFetcher_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockFetcher_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFetcher_Expecter) Close(ctx interface{}) *MockFetcher_Close_Call {
	return &MockFetcher_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockFetcher_Close_Call) Run(run func(ctx context.Context)) *MockFetcher_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFetcher_Close_Call) Return(err error) *MockFetcher_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFetcher_Close_Call) RunAndReturn(run func(ctx context.Context) error) *MockFetcher_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockTime provides a mock function for the type MockFetcher
func (_mock *MockFetcher) GetBlockTime() (time.Duration, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBlockTime")
	}

	var r0 time.Duration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (time.Duration, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFetcher_GetBlockTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockTime'
type MockFetcher_GetBlockTime_Call struct {
	*mock.Call
}

// GetBlockTime is a helper method to define mock.On call
func (_e *MockFetcher_Expecter) GetBlockTime() *MockFetcher_GetBlockTime_Call {
	return &MockFetcher_GetBlockTime_Call{Call: _e.mock.On("GetBlockTime")}
}

func (_c *MockFetcher_GetBlockTime_Call) Run(run func()) *MockFetcher_GetBlockTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFetcher_GetBlockTime_Call) Return(duration time.Duration, err error) *MockFetcher_GetBlockTime_Call {
	_c.Call.Return(duration, err)
	return _c
}

func (_c *MockFetcher_GetBlockTime_Call) RunAndReturn(run func() (time.Duration, error)) *MockFetcher_GetBlockTime_Call {
	_c.Call.Return(run)
	return _c
}

// GetCometNodeStatus provides a mock function for the type MockFetcher
func (_mock *MockFetcher) GetCometNodeStatus(rpcURL string) (*coretypes.ResultStatus, error) {
	ret := _mock.Called(rpcURL)

	if len(ret) == 0 {
		panic("no return value specified for GetCometNodeStatus")
	}

	var r0 *coretypes.ResultStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*coretypes.ResultStatus, error)); ok {
		return returnFunc(rpcURL)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *coretypes.ResultStatus); ok {
		r0 = returnFunc(rpcURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coretypes.ResultStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(rpcURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFetcher_GetCometNodeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCometNodeStatus'
type MockFetcher_GetCometNodeStatus_Call struct {
	*mock.Call
}

// GetCometNodeStatus is a helper method to define mock.On call
//   - rpcURL string
func (_e *MockFetcher_Expecter) GetCometNodeStatus(rpcURL interface{}) *MockFetcher_GetCometNodeStatus_Call {
	return &MockFetcher_GetCometNodeStatus_Call{Call: _e.mock.On("GetCometNodeStatus", rpcURL)}
}

func (_c *MockFetcher_GetCometNodeStatus_Call) Run(run func(rpcURL string)) *MockFetcher_GetCometNodeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFetcher_GetCometNodeStatus_Call) Return(resultStatus *coretypes.ResultStatus, err error) *MockFetcher_GetCometNodeStatus_Call {
	_c.Call.Return(resultStatus, err)
	return _c
}

func (_c *MockFetcher_GetCometNodeStatus_Call) RunAndReturn(run func(rpcURL string) (*coretypes.ResultStatus, error)) *MockFetcher_GetCometNodeStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetConsensusState provides a mock function for the type MockFetcher
func (_mock *MockFetcher) GetConsensusState() (*types.RoundState, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConsensusState")
	}

	var r0 *types.RoundState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*types.RoundState, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *types.RoundState); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.RoundState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFetcher_GetConsensusState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConsensusState'
type MockFetcher_GetConsensusState_Call struct {
	*mock.Call
}

// GetConsensusState is a helper method to define mock.On call
func (_e *MockFetcher_Expecter) GetConsensusState() *MockFetcher_GetConsensusState_Call {
	return &MockFetcher_GetConsensusState_Call{Call: _e.mock.On("GetConsensusState")}
}

func (_c *MockFetcher_GetConsensusState_Call) Run(run func()) *MockFetcher_GetConsensusState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFetcher_GetConsensusState_Call) Return(roundState *types.RoundState, err error) *MockFetcher_GetConsensusState_Call {
	_c.Call.Return(roundState, err)
	return _c
}

func (_c *MockFetcher_GetConsensusState_Call) RunAndReturn(run func() (*types.RoundState, error)) *MockFetcher_GetConsensusState_Call {
	_c.Call.Return(run)
	return _c
}

// GetNetInfo provides a mock function for the type MockFetcher
func (_mock *MockFetcher) GetNetInfo(rpcURL string) (*types0.NetInfo, error) {
	ret := _mock.Called(rpcURL)

	if len(ret) == 0 {
		panic("no return value specified for GetNetInfo")
	}

	var r0 *types0.NetInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*types0.NetInfo, error)); ok {
		return returnFunc(rpcURL)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *types0.NetInfo); ok {
		r0 = returnFunc(rpcURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types0.NetInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(rpcURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFetcher_GetNetInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNetInfo'
type MockFetcher_GetNetInfo_Call struct {
	*mock.Call
}

// GetNetInfo is a helper method to define mock.On call
//   - rpcURL string
func (_e *MockFetcher_Expecter) GetNetInfo(rpcURL interface{}) *MockFetcher_GetNetInfo_Call {
	return &MockFetcher_GetNetInfo_Call{Call: _e.mock.On("GetNetInfo", rpcURL)}
}

func (_c *MockFetcher_GetNetInfo_Call) Run(run func(rpcURL string)) *MockFetcher_GetNetInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFetcher_GetNetInfo_Call) Return(netInfo *types0.NetInfo, err error) *MockFetcher_GetNetInfo_Call {
	_c.Call.Return(netInfo, err)
	return _c
}

func (_c *MockFetcher_GetNetInfo_Call) RunAndReturn(run func(rpcURL string) (*types0.NetInfo, error)) *MockFetcher_GetNetInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpgradePlan provides a mock function for the type MockFetcher
func (_mock *MockFetcher) GetUpgradePlan() (*types0.Upgrade, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUpgradePlan")
	}

	var r0 *types0.Upgrade
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*types0.Upgrade, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *types0.Upgrade); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types0.Upgrade)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFetcher_GetUpgradePlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpgradePlan'
type MockFetcher_GetUpgradePlan_Call struct {
	*mock.Call
}

// GetUpgradePlan is a helper method to define mock.On call
func (_e *MockFetcher_Expecter) GetUpgradePlan() *MockFetcher_GetUpgradePlan_Call {
	return &MockFetcher_GetUpgradePlan_Call{Call: _e.mock.On("GetUpgradePlan")}
}

func (_c *MockFetcher_GetUpgradePlan_Call) Run(run func()) *MockFetcher_GetUpgradePlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFetcher_GetUpgradePlan_Call) Return(upgrade *types0.Upgrade, err error) *MockFetcher_GetUpgradePlan_Call {
	_c.Call.Return(upgrade, err)
	return _c
}

func (_c *MockFetcher_GetUpgradePlan_Call) RunAndReturn(run func() (*types0.Upgrade, error)) *MockFetcher_GetUpgradePlan_Call {
	_c.Call.Return(run)
	return _c
}

// GetValidators provides a mock function for the type MockFetcher
func (_mock *MockFetcher) GetValidators() ([]types0.TMValidator, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetValidators")
	}

	var r0 []types0.TMValidator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]types0.TMValidator, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []types0.TMValidator); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types0.TMValidator)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFetcher_GetValidators_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetValidators'
type MockFetcher_GetValidators_Call struct {
	*mock.Call
}

// GetValidators is a helper method to define mock.On call
func (_e *MockFetcher_Expecter) GetValidators() *MockFetcher_GetValidators_Call {
	return &MockFetcher_GetValidators_Call{Call: _e.mock.On("GetValidators")}
}

func (_c *MockFetcher_GetValidators_Call) Run(run func()) *MockFetcher_GetValidators_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFetcher_GetValidators_Call) Return(tMValidators []types0.TMValidator, err error) *MockFetcher_GetValidators_Call {
	_c.Call.Return(tMValidators, err)
	return _c
}

func (_c *MockFetcher_GetValidators_Call) RunAndReturn(run func() ([]types0.TMValidator, error)) *MockFetcher_GetValidators_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockFetcher
//
// NOTE: hand-patched after mockery codegen. The mockery v3.7 testify
// template generates `_mock.Called(mb, events)` here, passing the
// variadic slice as a single argument. The matching EXPECT().Subscribe
// helper below already spreads its variadic arguments via
// `append([]interface{}{mb}, events...)...`, so the two would never
// agree on argument count and any expectation set with concrete event
// names would silently fail to match. Spread events into individual
// interface{} values so the registered call shape matches the
// expectation. If/when mockery is regenerated this needs to be
// re-applied.
func (_mock *MockFetcher) Subscribe(mb *utils.Mailbox[types1.TMEventData], events ...string) {
	_ca := []interface{}{mb}
	for _, e := range events {
		_ca = append(_ca, e)
	}
	_mock.Called(_ca...)
}

// MockFetcher_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockFetcher_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - mb *utils.Mailbox[types1.TMEventData]
//   - events ...string
func (_e *MockFetcher_Expecter) Subscribe(mb interface{}, events ...interface{}) *MockFetcher_Subscribe_Call {
	return &MockFetcher_Subscribe_Call{Call: _e.mock.On("Subscribe",
		append([]interface{}{mb}, events...)...)}
}

func (_c *MockFetcher_Subscribe_Call) Run(run func(mb *utils.Mailbox[types1.TMEventData], events ...string)) *MockFetcher_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *utils.Mailbox[types1.TMEventData]
		if args[0] != nil {
			arg0 = args[0].(*utils.Mailbox[types1.TMEventData])
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockFetcher_Subscribe_Call) Return() *MockFetcher_Subscribe_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFetcher_Subscribe_Call) RunAndReturn(run func(mb *utils.Mailbox[types1.TMEventData], events ...string)) *MockFetcher_Subscribe_Call {
	_c.Run(run)
	return _c
}
