// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getAllValidatorsSigningEfficiency = `-- name: GetAllValidatorsSigningEfficiency :many
WITH validator_participation AS (
    SELECT 
        vals.hex_address,
        vals.moniker,
        h.height,
        CASE WHEN v.id IS NOT NULL THEN 1 ELSE 0 END as participated
    FROM validators vals
    CROSS JOIN heights h
    LEFT JOIN votes v ON vals.hex_address = v.validator_hex_address AND h.height = v.height
    WHERE h.block_time >= ? AND h.block_time <= ?
)
SELECT 
    hex_address,
    moniker,
    COUNT(*) as total_blocks,
    SUM(participated) as blocks_signed,
    COUNT(*) - SUM(participated) as blocks_missed,
    ROUND(100.0 * SUM(participated) / COUNT(*), 2) as signing_efficiency
FROM validator_participation 
GROUP BY hex_address, moniker
ORDER BY signing_efficiency DESC
`

type GetAllValidatorsSigningEfficiencyParams struct {
	BlockTime   sql.NullTime `json:"block_time"`
	BlockTime_2 sql.NullTime `json:"block_time_2"`
}

type GetAllValidatorsSigningEfficiencyRow struct {
	HexAddress        string          `json:"hex_address"`
	Moniker           sql.NullString  `json:"moniker"`
	TotalBlocks       int64           `json:"total_blocks"`
	BlocksSigned      sql.NullFloat64 `json:"blocks_signed"`
	BlocksMissed      int64           `json:"blocks_missed"`
	SigningEfficiency float64         `json:"signing_efficiency"`
}

// Get signing efficiency for all validators over a time window
func (q *Queries) GetAllValidatorsSigningEfficiency(ctx context.Context, arg GetAllValidatorsSigningEfficiencyParams) ([]GetAllValidatorsSigningEfficiencyRow, error) {
	rows, err := q.query(ctx, q.getAllValidatorsSigningEfficiencyStmt, getAllValidatorsSigningEfficiency, arg.BlockTime, arg.BlockTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllValidatorsSigningEfficiencyRow{}
	for rows.Next() {
		var i GetAllValidatorsSigningEfficiencyRow
		if err := rows.Scan(
			&i.HexAddress,
			&i.Moniker,
			&i.TotalBlocks,
			&i.BlocksSigned,
			&i.BlocksMissed,
			&i.SigningEfficiency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProposerPerformance = `-- name: GetProposerPerformance :one
SELECT 
    COUNT(*) as blocks_proposed,
    COUNT(CASE WHEN r.proposer_address = ? THEN 1 END) as successful_proposals,
    ROUND(100.0 * COUNT(CASE WHEN r.proposer_address = ? THEN 1 END) / COUNT(*), 2) as proposal_success_rate
FROM rounds r
JOIN heights h ON r.height = h.height
WHERE r.proposer_address = ? AND h.block_time >= ? AND h.block_time <= ?
`

type GetProposerPerformanceParams struct {
	ProposerAddress   sql.NullString `json:"proposer_address"`
	ProposerAddress_2 sql.NullString `json:"proposer_address_2"`
	ProposerAddress_3 sql.NullString `json:"proposer_address_3"`
	BlockTime         sql.NullTime   `json:"block_time"`
	BlockTime_2       sql.NullTime   `json:"block_time_2"`
}

type GetProposerPerformanceRow struct {
	BlocksProposed      int64   `json:"blocks_proposed"`
	SuccessfulProposals int64   `json:"successful_proposals"`
	ProposalSuccessRate float64 `json:"proposal_success_rate"`
}

// Calculate proposer performance metrics (when validator is selected as proposer)
func (q *Queries) GetProposerPerformance(ctx context.Context, arg GetProposerPerformanceParams) (GetProposerPerformanceRow, error) {
	row := q.queryRow(ctx, q.getProposerPerformanceStmt, getProposerPerformance,
		arg.ProposerAddress,
		arg.ProposerAddress_2,
		arg.ProposerAddress_3,
		arg.BlockTime,
		arg.BlockTime_2,
	)
	var i GetProposerPerformanceRow
	err := row.Scan(&i.BlocksProposed, &i.SuccessfulProposals, &i.ProposalSuccessRate)
	return i, err
}

const getValidatorConsensusParticipation = `-- name: GetValidatorConsensusParticipation :one
WITH vote_participation AS (
    SELECT 
        r.height,
        r.round_number,
        COUNT(CASE WHEN v.vote_type = 1 THEN 1 END) as prevotes,
        COUNT(CASE WHEN v.vote_type = 2 THEN 1 END) as precommits,
        COUNT(DISTINCT r.round_number) as total_rounds
    FROM rounds r
    LEFT JOIN votes v ON r.height = v.height AND r.round_number = v.round_number AND v.validator_hex_address = ?
    LEFT JOIN heights h ON r.height = h.height
    WHERE h.block_time >= ? AND h.block_time <= ?
    GROUP BY r.height, r.round_number
)
SELECT 
    COALESCE(COUNT(*), 0) as total_rounds,
    COALESCE(SUM(CASE WHEN prevotes > 0 THEN 1 ELSE 0 END), 0) as rounds_with_prevote,
    COALESCE(SUM(CASE WHEN precommits > 0 THEN 1 ELSE 0 END), 0) as rounds_with_precommit,
    COALESCE(ROUND(100.0 * SUM(CASE WHEN prevotes > 0 THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 2), 0.0) as prevote_rate,
    COALESCE(ROUND(100.0 * SUM(CASE WHEN precommits > 0 THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 2), 0.0) as precommit_rate
FROM vote_participation
`

type GetValidatorConsensusParticipationParams struct {
	ValidatorHexAddress string       `json:"validator_hex_address"`
	BlockTime           sql.NullTime `json:"block_time"`
	BlockTime_2         sql.NullTime `json:"block_time_2"`
}

type GetValidatorConsensusParticipationRow struct {
	TotalRounds         interface{} `json:"total_rounds"`
	RoundsWithPrevote   interface{} `json:"rounds_with_prevote"`
	RoundsWithPrecommit interface{} `json:"rounds_with_precommit"`
	PrevoteRate         interface{} `json:"prevote_rate"`
	PrecommitRate       interface{} `json:"precommit_rate"`
}

// Calculate consensus participation rates for prevotes and precommits
func (q *Queries) GetValidatorConsensusParticipation(ctx context.Context, arg GetValidatorConsensusParticipationParams) (GetValidatorConsensusParticipationRow, error) {
	row := q.queryRow(ctx, q.getValidatorConsensusParticipationStmt, getValidatorConsensusParticipation, arg.ValidatorHexAddress, arg.BlockTime, arg.BlockTime_2)
	var i GetValidatorConsensusParticipationRow
	err := row.Scan(
		&i.TotalRounds,
		&i.RoundsWithPrevote,
		&i.RoundsWithPrecommit,
		&i.PrevoteRate,
		&i.PrecommitRate,
	)
	return i, err
}

const getValidatorMissedBlockStreaks = `-- name: GetValidatorMissedBlockStreaks :many
WITH block_sequence AS (
    SELECT 
        h.height,
        h.block_time,
        CASE WHEN v.id IS NULL THEN 1 ELSE 0 END as missed,
        ROW_NUMBER() OVER (ORDER BY h.height) as rn
    FROM heights h
    LEFT JOIN votes v ON h.height = v.height AND v.validator_hex_address = ?
    WHERE h.block_time >= ? AND h.block_time <= ?
),
miss_groups AS (
    SELECT 
        height,
        block_time,
        missed,
        rn - ROW_NUMBER() OVER (PARTITION BY missed ORDER BY height) as grp
    FROM block_sequence
    WHERE missed = 1
)
SELECT 
    COUNT(*) as consecutive_misses,
    MIN(height) as streak_start_height,
    MAX(height) as streak_end_height,
    MIN(block_time) as streak_start_time,
    MAX(block_time) as streak_end_time
FROM miss_groups 
GROUP BY grp
HAVING COUNT(*) > 0
ORDER BY consecutive_misses DESC
`

type GetValidatorMissedBlockStreaksParams struct {
	ValidatorHexAddress string       `json:"validator_hex_address"`
	BlockTime           sql.NullTime `json:"block_time"`
	BlockTime_2         sql.NullTime `json:"block_time_2"`
}

type GetValidatorMissedBlockStreaksRow struct {
	ConsecutiveMisses int64       `json:"consecutive_misses"`
	StreakStartHeight interface{} `json:"streak_start_height"`
	StreakEndHeight   interface{} `json:"streak_end_height"`
	StreakStartTime   interface{} `json:"streak_start_time"`
	StreakEndTime     interface{} `json:"streak_end_time"`
}

// Find consecutive missed block sequences for a validator
func (q *Queries) GetValidatorMissedBlockStreaks(ctx context.Context, arg GetValidatorMissedBlockStreaksParams) ([]GetValidatorMissedBlockStreaksRow, error) {
	rows, err := q.query(ctx, q.getValidatorMissedBlockStreaksStmt, getValidatorMissedBlockStreaks, arg.ValidatorHexAddress, arg.BlockTime, arg.BlockTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetValidatorMissedBlockStreaksRow{}
	for rows.Next() {
		var i GetValidatorMissedBlockStreaksRow
		if err := rows.Scan(
			&i.ConsecutiveMisses,
			&i.StreakStartHeight,
			&i.StreakEndHeight,
			&i.StreakStartTime,
			&i.StreakEndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidatorPerformanceTimeSeries = `-- name: GetValidatorPerformanceTimeSeries :many
WITH time_buckets AS (
    SELECT 
        datetime(h.block_time, 'start of hour') as time_bucket,
        COUNT(*) as blocks_in_bucket,
        SUM(CASE WHEN v.id IS NOT NULL THEN 1 ELSE 0 END) as blocks_signed
    FROM heights h
    LEFT JOIN votes v ON h.height = v.height AND v.validator_hex_address = ?
    WHERE h.block_time >= ? AND h.block_time <= ?
    GROUP BY datetime(h.block_time, 'start of hour')
)
SELECT 
    time_bucket,
    COALESCE(blocks_in_bucket, 0) as blocks_in_bucket,
    COALESCE(blocks_signed, 0) as blocks_signed,
    COALESCE(blocks_in_bucket - blocks_signed, 0) as blocks_missed,
    COALESCE(ROUND(100.0 * blocks_signed / NULLIF(blocks_in_bucket, 0), 2), 0.0) as signing_efficiency
FROM time_buckets 
ORDER BY time_bucket
`

type GetValidatorPerformanceTimeSeriesParams struct {
	ValidatorHexAddress string       `json:"validator_hex_address"`
	BlockTime           sql.NullTime `json:"block_time"`
	BlockTime_2         sql.NullTime `json:"block_time_2"`
}

type GetValidatorPerformanceTimeSeriesRow struct {
	TimeBucket        interface{} `json:"time_bucket"`
	BlocksInBucket    int64       `json:"blocks_in_bucket"`
	BlocksSigned      float64     `json:"blocks_signed"`
	BlocksMissed      interface{} `json:"blocks_missed"`
	SigningEfficiency interface{} `json:"signing_efficiency"`
}

// Get signing efficiency over time buckets (hourly)
func (q *Queries) GetValidatorPerformanceTimeSeries(ctx context.Context, arg GetValidatorPerformanceTimeSeriesParams) ([]GetValidatorPerformanceTimeSeriesRow, error) {
	rows, err := q.query(ctx, q.getValidatorPerformanceTimeSeriesStmt, getValidatorPerformanceTimeSeries, arg.ValidatorHexAddress, arg.BlockTime, arg.BlockTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetValidatorPerformanceTimeSeriesRow{}
	for rows.Next() {
		var i GetValidatorPerformanceTimeSeriesRow
		if err := rows.Scan(
			&i.TimeBucket,
			&i.BlocksInBucket,
			&i.BlocksSigned,
			&i.BlocksMissed,
			&i.SigningEfficiency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidatorRanking = `-- name: GetValidatorRanking :many
WITH validator_metrics AS (
    SELECT 
        vals.hex_address,
        vals.moniker,
        -- Block signing metrics
        COUNT(h.height) as total_blocks,
        COUNT(v.id) as blocks_signed,
        ROUND(100.0 * COUNT(v.id) / COUNT(h.height), 2) as signing_efficiency,
        
        -- Consensus participation
        COUNT(CASE WHEN v.vote_type = 1 THEN 1 END) as prevotes_cast,
        COUNT(CASE WHEN v.vote_type = 2 THEN 1 END) as precommits_cast,
        
        -- Latest voting power
        COALESCE(MAX(vs.voting_power), 0) as voting_power
    FROM validators vals
    CROSS JOIN heights h
    LEFT JOIN votes v ON vals.hex_address = v.validator_hex_address AND h.height = v.height
    LEFT JOIN validator_snapshots vs ON vals.hex_address = vs.validator_hex_address AND h.height = vs.height
    WHERE h.block_time >= ? AND h.block_time <= ?
    GROUP BY vals.hex_address, vals.moniker
)
SELECT 
    hex_address,
    moniker,
    total_blocks,
    blocks_signed,
    total_blocks - blocks_signed as blocks_missed,
    signing_efficiency,
    prevotes_cast,
    precommits_cast,
    voting_power,
    RANK() OVER (ORDER BY signing_efficiency DESC, voting_power DESC) as efficiency_rank
FROM validator_metrics
ORDER BY efficiency_rank
`

type GetValidatorRankingParams struct {
	BlockTime   sql.NullTime `json:"block_time"`
	BlockTime_2 sql.NullTime `json:"block_time_2"`
}

type GetValidatorRankingRow struct {
	HexAddress        string         `json:"hex_address"`
	Moniker           sql.NullString `json:"moniker"`
	TotalBlocks       int64          `json:"total_blocks"`
	BlocksSigned      int64          `json:"blocks_signed"`
	BlocksMissed      int64          `json:"blocks_missed"`
	SigningEfficiency float64        `json:"signing_efficiency"`
	PrevotesCast      int64          `json:"prevotes_cast"`
	PrecommitsCast    int64          `json:"precommits_cast"`
	VotingPower       interface{}    `json:"voting_power"`
	EfficiencyRank    interface{}    `json:"efficiency_rank"`
}

// Get validator performance ranking with multiple metrics
func (q *Queries) GetValidatorRanking(ctx context.Context, arg GetValidatorRankingParams) ([]GetValidatorRankingRow, error) {
	rows, err := q.query(ctx, q.getValidatorRankingStmt, getValidatorRanking, arg.BlockTime, arg.BlockTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetValidatorRankingRow{}
	for rows.Next() {
		var i GetValidatorRankingRow
		if err := rows.Scan(
			&i.HexAddress,
			&i.Moniker,
			&i.TotalBlocks,
			&i.BlocksSigned,
			&i.BlocksMissed,
			&i.SigningEfficiency,
			&i.PrevotesCast,
			&i.PrecommitsCast,
			&i.VotingPower,
			&i.EfficiencyRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidatorSigningEfficiency = `-- name: GetValidatorSigningEfficiency :one
WITH block_participation AS (
    SELECT 
        h.height,
        h.block_time,
        COUNT(v.id) as votes_cast,
        CASE WHEN COUNT(v.id) > 0 THEN 1 ELSE 0 END as participated
    FROM heights h 
    LEFT JOIN votes v ON h.height = v.height AND v.validator_hex_address = ?
    WHERE h.block_time >= ? AND h.block_time <= ?
    GROUP BY h.height, h.block_time
)
SELECT 
    COALESCE(COUNT(*), 0) as total_blocks,
    COALESCE(SUM(participated), 0) as blocks_signed,
    COALESCE(COUNT(*) - SUM(participated), 0) as blocks_missed,
    COALESCE(ROUND(100.0 * SUM(participated) / NULLIF(COUNT(*), 0), 2), 0.0) as signing_efficiency
FROM block_participation
`

type GetValidatorSigningEfficiencyParams struct {
	ValidatorHexAddress string       `json:"validator_hex_address"`
	BlockTime           sql.NullTime `json:"block_time"`
	BlockTime_2         sql.NullTime `json:"block_time_2"`
}

type GetValidatorSigningEfficiencyRow struct {
	TotalBlocks       interface{} `json:"total_blocks"`
	BlocksSigned      interface{} `json:"blocks_signed"`
	BlocksMissed      interface{} `json:"blocks_missed"`
	SigningEfficiency interface{} `json:"signing_efficiency"`
}

// Calculate signing efficiency for a validator over a time window
func (q *Queries) GetValidatorSigningEfficiency(ctx context.Context, arg GetValidatorSigningEfficiencyParams) (GetValidatorSigningEfficiencyRow, error) {
	row := q.queryRow(ctx, q.getValidatorSigningEfficiencyStmt, getValidatorSigningEfficiency, arg.ValidatorHexAddress, arg.BlockTime, arg.BlockTime_2)
	var i GetValidatorSigningEfficiencyRow
	err := row.Scan(
		&i.TotalBlocks,
		&i.BlocksSigned,
		&i.BlocksMissed,
		&i.SigningEfficiency,
	)
	return i, err
}

const getValidatorUptime = `-- name: GetValidatorUptime :one
WITH block_stats AS (
    SELECT 
        COUNT(*) as total_blocks_in_window,
        COUNT(v.id) as blocks_participated,
        MIN(h.block_time) as window_start,
        MAX(h.block_time) as window_end
    FROM heights h
    LEFT JOIN votes v ON h.height = v.height AND v.validator_hex_address = ?
    WHERE h.block_time >= ? AND h.block_time <= ?
)
SELECT 
    COALESCE(bs.total_blocks_in_window, 0) as total_blocks_in_window,
    COALESCE(bs.blocks_participated, 0) as blocks_participated,
    COALESCE(bs.total_blocks_in_window - bs.blocks_participated, 0) as blocks_missed,
    COALESCE(ROUND(100.0 * bs.blocks_participated / NULLIF(bs.total_blocks_in_window, 0), 2), 0.0) as uptime_percentage,
    bs.window_start,
    bs.window_end
FROM block_stats bs
`

type GetValidatorUptimeParams struct {
	ValidatorHexAddress string       `json:"validator_hex_address"`
	BlockTime           sql.NullTime `json:"block_time"`
	BlockTime_2         sql.NullTime `json:"block_time_2"`
}

type GetValidatorUptimeRow struct {
	TotalBlocksInWindow int64       `json:"total_blocks_in_window"`
	BlocksParticipated  int64       `json:"blocks_participated"`
	BlocksMissed        interface{} `json:"blocks_missed"`
	UptimePercentage    interface{} `json:"uptime_percentage"`
	WindowStart         interface{} `json:"window_start"`
	WindowEnd           interface{} `json:"window_end"`
}

// Calculate validator uptime metrics over time window
func (q *Queries) GetValidatorUptime(ctx context.Context, arg GetValidatorUptimeParams) (GetValidatorUptimeRow, error) {
	row := q.queryRow(ctx, q.getValidatorUptimeStmt, getValidatorUptime, arg.ValidatorHexAddress, arg.BlockTime, arg.BlockTime_2)
	var i GetValidatorUptimeRow
	err := row.Scan(
		&i.TotalBlocksInWindow,
		&i.BlocksParticipated,
		&i.BlocksMissed,
		&i.UptimePercentage,
		&i.WindowStart,
		&i.WindowEnd,
	)
	return i, err
}
