// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics_live.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getMaxStoredHeight = `-- name: GetMaxStoredHeight :one
SELECT COALESCE(MAX(height), 0) AS height FROM heights
`

func (q *Queries) GetMaxStoredHeight(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxStoredHeight)
	var height interface{}
	err := row.Scan(&height)
	return height, err
}

const getProposerPerformanceByHeight = `-- name: GetProposerPerformanceByHeight :many
SELECT
    r.proposer_address AS hex_address,
    COUNT(*) AS blocks_proposed
FROM rounds r
WHERE r.height >= ? AND r.height <= ? AND r.proposer_address IS NOT NULL
GROUP BY r.proposer_address
`

type GetProposerPerformanceByHeightParams struct {
	Height   int64 `json:"height"`
	Height_2 int64 `json:"height_2"`
}

type GetProposerPerformanceByHeightRow struct {
	HexAddress     sql.NullString `json:"hex_address"`
	BlocksProposed int64          `json:"blocks_proposed"`
}

// Per-validator proposer share over a height window: how often each validator
// proposed relative to all proposing opportunities.
func (q *Queries) GetProposerPerformanceByHeight(ctx context.Context, arg GetProposerPerformanceByHeightParams) ([]GetProposerPerformanceByHeightRow, error) {
	rows, err := q.db.QueryContext(ctx, getProposerPerformanceByHeight, arg.Height, arg.Height_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProposerPerformanceByHeightRow{}
	for rows.Next() {
		var i GetProposerPerformanceByHeightRow
		if err := rows.Scan(&i.HexAddress, &i.BlocksProposed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidatorRankingByHeight = `-- name: GetValidatorRankingByHeight :many
WITH validator_metrics AS (
    SELECT
        vals.hex_address,
        vals.moniker,
        COUNT(DISTINCT h.height) AS total_blocks,
        COUNT(DISTINCT CASE WHEN v.id IS NOT NULL THEN h.height END) AS blocks_signed,
        COALESCE(ROUND(
            100.0 * COUNT(DISTINCT CASE WHEN v.id IS NOT NULL THEN h.height END)
                  / NULLIF(COUNT(DISTINCT h.height), 0), 2), 0.0) AS signing_efficiency,
        COUNT(CASE WHEN v.vote_type = 1 THEN 1 END) AS prevotes_cast,
        COUNT(CASE WHEN v.vote_type = 2 THEN 1 END) AS precommits_cast,
        COALESCE(MAX(vs.voting_power), 0) AS voting_power
    FROM validators vals
    CROSS JOIN heights h
    LEFT JOIN votes v ON vals.hex_address = v.validator_hex_address AND h.height = v.height
    LEFT JOIN validator_snapshots vs ON vals.hex_address = vs.validator_hex_address AND h.height = vs.height
    WHERE h.height >= ? AND h.height <= ?
    GROUP BY vals.hex_address, vals.moniker
)
SELECT
    hex_address, moniker, total_blocks, blocks_signed,
    total_blocks - blocks_signed AS blocks_missed,
    signing_efficiency, prevotes_cast, precommits_cast, voting_power
FROM validator_metrics
ORDER BY signing_efficiency DESC
`

type GetValidatorRankingByHeightParams struct {
	Height   int64 `json:"height"`
	Height_2 int64 `json:"height_2"`
}

type GetValidatorRankingByHeightRow struct {
	HexAddress        string         `json:"hex_address"`
	Moniker           sql.NullString `json:"moniker"`
	TotalBlocks       int64          `json:"total_blocks"`
	BlocksSigned      int64          `json:"blocks_signed"`
	BlocksMissed      int64          `json:"blocks_missed"`
	SigningEfficiency interface{}    `json:"signing_efficiency"`
	PrevotesCast      int64          `json:"prevotes_cast"`
	PrecommitsCast    int64          `json:"precommits_cast"`
	VotingPower       interface{}    `json:"voting_power"`
}

// Signing efficiency + participation for all validators over a height window
// [min_height, max_height]. Counts distinct heights to avoid the prevote+precommit
// double-count (see analytics.sql notes).
func (q *Queries) GetValidatorRankingByHeight(ctx context.Context, arg GetValidatorRankingByHeightParams) ([]GetValidatorRankingByHeightRow, error) {
	rows, err := q.db.QueryContext(ctx, getValidatorRankingByHeight, arg.Height, arg.Height_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetValidatorRankingByHeightRow{}
	for rows.Next() {
		var i GetValidatorRankingByHeightRow
		if err := rows.Scan(
			&i.HexAddress,
			&i.Moniker,
			&i.TotalBlocks,
			&i.BlocksSigned,
			&i.BlocksMissed,
			&i.SigningEfficiency,
			&i.PrevotesCast,
			&i.PrecommitsCast,
			&i.VotingPower,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVoteArrivalByHeight = `-- name: GetVoteArrivalByHeight :many
SELECT
    v.validator_hex_address AS hex_address,
    v.vote_type AS vote_type,
    COUNT(*) AS samples,
    COALESCE(AVG((julianday(v.timestamp) - julianday(r.start_time)) * 86400.0), 0.0) AS avg_secs,
    COALESCE(MAX((julianday(v.timestamp) - julianday(r.start_time)) * 86400.0), 0.0) AS max_secs
FROM votes v
JOIN rounds r ON v.height = r.height AND v.round_number = r.round_number
WHERE v.height >= ? AND v.height <= ?
  AND v.timestamp IS NOT NULL AND r.start_time IS NOT NULL
GROUP BY v.validator_hex_address, v.vote_type
`

type GetVoteArrivalByHeightParams struct {
	Height   int64 `json:"height"`
	Height_2 int64 `json:"height_2"`
}

type GetVoteArrivalByHeightRow struct {
	HexAddress string      `json:"hex_address"`
	VoteType   int64       `json:"vote_type"`
	Samples    int64       `json:"samples"`
	AvgSecs    interface{} `json:"avg_secs"`
	MaxSecs    interface{} `json:"max_secs"`
}

// Per-validator, per-vote-type arrival latency relative to round start, using
// locally-observed timestamps (single-vantage). Returns avg/max in seconds.
func (q *Queries) GetVoteArrivalByHeight(ctx context.Context, arg GetVoteArrivalByHeightParams) ([]GetVoteArrivalByHeightRow, error) {
	rows, err := q.db.QueryContext(ctx, getVoteArrivalByHeight, arg.Height, arg.Height_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVoteArrivalByHeightRow{}
	for rows.Next() {
		var i GetVoteArrivalByHeightRow
		if err := rows.Scan(
			&i.HexAddress,
			&i.VoteType,
			&i.Samples,
			&i.AvgSecs,
			&i.MaxSecs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
