// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: debug.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countConsensusEvents = `-- name: CountConsensusEvents :one
SELECT COUNT(*) FROM consensus_events
`

func (q *Queries) CountConsensusEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConsensusEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHeights = `-- name: CountHeights :one
SELECT COUNT(*) FROM heights
`

func (q *Queries) CountHeights(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHeights)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHeightsInTimeWindow = `-- name: CountHeightsInTimeWindow :one
SELECT COUNT(*) FROM heights WHERE block_time >= ? AND block_time <= ?
`

type CountHeightsInTimeWindowParams struct {
	BlockTime   sql.NullTime `json:"block_time"`
	BlockTime_2 sql.NullTime `json:"block_time_2"`
}

func (q *Queries) CountHeightsInTimeWindow(ctx context.Context, arg CountHeightsInTimeWindowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHeightsInTimeWindow, arg.BlockTime, arg.BlockTime_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRounds = `-- name: CountRounds :one
SELECT COUNT(*) FROM rounds
`

func (q *Queries) CountRounds(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRounds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countValidatorSnapshots = `-- name: CountValidatorSnapshots :one
SELECT COUNT(*) FROM validator_snapshots
`

func (q *Queries) CountValidatorSnapshots(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countValidatorSnapshots)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countValidators = `-- name: CountValidators :one

SELECT COUNT(*) FROM validators
`

// COUNT helpers - one per table because sqlc can't parameterize
// table identifiers.
func (q *Queries) CountValidators(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countValidators)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVotes = `-- name: CountVotes :one
SELECT COUNT(*) FROM votes
`

func (q *Queries) CountVotes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVotes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVotesForValidatorInTimeWindow = `-- name: CountVotesForValidatorInTimeWindow :one
SELECT COUNT(*)
FROM votes v
JOIN heights h ON v.height = h.height
JOIN validators val ON v.validator_hex_address = val.hex_address
WHERE val.operator_address = ? AND h.block_time >= ? AND h.block_time <= ?
`

type CountVotesForValidatorInTimeWindowParams struct {
	OperatorAddress string       `json:"operator_address"`
	BlockTime       sql.NullTime `json:"block_time"`
	BlockTime_2     sql.NullTime `json:"block_time_2"`
}

func (q *Queries) CountVotesForValidatorInTimeWindow(ctx context.Context, arg CountVotesForValidatorInTimeWindowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVotesForValidatorInTimeWindow, arg.OperatorAddress, arg.BlockTime, arg.BlockTime_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAllValidators = `-- name: ListAllValidators :many
SELECT operator_address, moniker FROM validators ORDER BY operator_address
`

type ListAllValidatorsRow struct {
	OperatorAddress string         `json:"operator_address"`
	Moniker         sql.NullString `json:"moniker"`
}

func (q *Queries) ListAllValidators(ctx context.Context) ([]ListAllValidatorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllValidators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllValidatorsRow{}
	for rows.Next() {
		var i ListAllValidatorsRow
		if err := rows.Scan(&i.OperatorAddress, &i.Moniker); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sampleHeights = `-- name: SampleHeights :many
SELECT height, block_time, proposer_address FROM heights ORDER BY height DESC LIMIT 5
`

type SampleHeightsRow struct {
	Height          int64          `json:"height"`
	BlockTime       sql.NullTime   `json:"block_time"`
	ProposerAddress sql.NullString `json:"proposer_address"`
}

func (q *Queries) SampleHeights(ctx context.Context) ([]SampleHeightsRow, error) {
	rows, err := q.db.QueryContext(ctx, sampleHeights)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SampleHeightsRow{}
	for rows.Next() {
		var i SampleHeightsRow
		if err := rows.Scan(&i.Height, &i.BlockTime, &i.ProposerAddress); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sampleValidators = `-- name: SampleValidators :many
SELECT operator_address, moniker, voting_power FROM validators LIMIT 5
`

type SampleValidatorsRow struct {
	OperatorAddress string         `json:"operator_address"`
	Moniker         sql.NullString `json:"moniker"`
	VotingPower     int64          `json:"voting_power"`
}

func (q *Queries) SampleValidators(ctx context.Context) ([]SampleValidatorsRow, error) {
	rows, err := q.db.QueryContext(ctx, sampleValidators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SampleValidatorsRow{}
	for rows.Next() {
		var i SampleValidatorsRow
		if err := rows.Scan(&i.OperatorAddress, &i.Moniker, &i.VotingPower); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sampleVotes = `-- name: SampleVotes :many
SELECT height, round_number, validator_hex_address, vote_type, timestamp FROM votes LIMIT 5
`

type SampleVotesRow struct {
	Height              int64        `json:"height"`
	RoundNumber         int64        `json:"round_number"`
	ValidatorHexAddress string       `json:"validator_hex_address"`
	VoteType            int64        `json:"vote_type"`
	Timestamp           sql.NullTime `json:"timestamp"`
}

func (q *Queries) SampleVotes(ctx context.Context) ([]SampleVotesRow, error) {
	rows, err := q.db.QueryContext(ctx, sampleVotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SampleVotesRow{}
	for rows.Next() {
		var i SampleVotesRow
		if err := rows.Scan(
			&i.Height,
			&i.RoundNumber,
			&i.ValidatorHexAddress,
			&i.VoteType,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sampleVotesForValidator = `-- name: SampleVotesForValidator :many
SELECT v.height, v.round_number, v.vote_type, v.timestamp, h.block_time
FROM votes v
JOIN heights h ON v.height = h.height
JOIN validators val ON v.validator_hex_address = val.hex_address
WHERE val.operator_address = ?
ORDER BY v.height DESC
LIMIT ?
`

type SampleVotesForValidatorParams struct {
	OperatorAddress string `json:"operator_address"`
	Limit           int64  `json:"limit"`
}

type SampleVotesForValidatorRow struct {
	Height      int64        `json:"height"`
	RoundNumber int64        `json:"round_number"`
	VoteType    int64        `json:"vote_type"`
	Timestamp   sql.NullTime `json:"timestamp"`
	BlockTime   sql.NullTime `json:"block_time"`
}

func (q *Queries) SampleVotesForValidator(ctx context.Context, arg SampleVotesForValidatorParams) ([]SampleVotesForValidatorRow, error) {
	rows, err := q.db.QueryContext(ctx, sampleVotesForValidator, arg.OperatorAddress, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SampleVotesForValidatorRow{}
	for rows.Next() {
		var i SampleVotesForValidatorRow
		if err := rows.Scan(
			&i.Height,
			&i.RoundNumber,
			&i.VoteType,
			&i.Timestamp,
			&i.BlockTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchValidatorsByOperatorOrMoniker = `-- name: SearchValidatorsByOperatorOrMoniker :many
SELECT operator_address, moniker, voting_power
FROM validators
WHERE operator_address LIKE ? OR LOWER(moniker) LIKE LOWER(?)
ORDER BY operator_address
`

type SearchValidatorsByOperatorOrMonikerParams struct {
	OperatorAddress string `json:"operator_address"`
	LOWER           string `json:"LOWER"`
}

type SearchValidatorsByOperatorOrMonikerRow struct {
	OperatorAddress string         `json:"operator_address"`
	Moniker         sql.NullString `json:"moniker"`
	VotingPower     int64          `json:"voting_power"`
}

func (q *Queries) SearchValidatorsByOperatorOrMoniker(ctx context.Context, arg SearchValidatorsByOperatorOrMonikerParams) ([]SearchValidatorsByOperatorOrMonikerRow, error) {
	rows, err := q.db.QueryContext(ctx, searchValidatorsByOperatorOrMoniker, arg.OperatorAddress, arg.LOWER)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchValidatorsByOperatorOrMonikerRow{}
	for rows.Next() {
		var i SearchValidatorsByOperatorOrMonikerRow
		if err := rows.Scan(&i.OperatorAddress, &i.Moniker, &i.VotingPower); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const validatorExistsByOperator = `-- name: ValidatorExistsByOperator :one
SELECT COUNT(*) FROM validators WHERE operator_address = ?
`

func (q *Queries) ValidatorExistsByOperator(ctx context.Context, operatorAddress string) (int64, error) {
	row := q.db.QueryRowContext(ctx, validatorExistsByOperator, operatorAddress)
	var count int64
	err := row.Scan(&count)
	return count, err
}
