// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

type ConsensusEvent struct {
	ID          int64          `json:"id"`
	Height      int64          `json:"height"`
	RoundNumber int64          `json:"round_number"`
	EventType   string         `json:"event_type"`
	EventData   sql.NullString `json:"event_data"`
	Timestamp   time.Time      `json:"timestamp"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Height struct {
	Height          int64          `json:"height"`
	BlockHash       sql.NullString `json:"block_hash"`
	BlockTime       sql.NullTime   `json:"block_time"`
	ProposerAddress sql.NullString `json:"proposer_address"`
	TotalValidators sql.NullInt64  `json:"total_validators"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type Round struct {
	ID              int64          `json:"id"`
	Height          int64          `json:"height"`
	RoundNumber     int64          `json:"round_number"`
	Step            sql.NullInt64  `json:"step"`
	StartTime       sql.NullTime   `json:"start_time"`
	ProposerAddress sql.NullString `json:"proposer_address"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type Validator struct {
	ID          int64          `json:"id"`
	Address     string         `json:"address"`
	PublicKey   string         `json:"public_key"`
	VotingPower int64          `json:"voting_power"`
	Moniker     sql.NullString `json:"moniker"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type ValidatorSnapshot struct {
	ID                 int64           `json:"id"`
	Height             int64           `json:"height"`
	ValidatorAddress   string          `json:"validator_address"`
	VotingPower        int64           `json:"voting_power"`
	VotingPowerPercent sql.NullFloat64 `json:"voting_power_percent"`
	IsProposer         sql.NullBool    `json:"is_proposer"`
	CreatedAt          sql.NullTime    `json:"created_at"`
}

type Vote struct {
	ID               int64          `json:"id"`
	Height           int64          `json:"height"`
	RoundNumber      int64          `json:"round_number"`
	ValidatorAddress string         `json:"validator_address"`
	VoteType         int64          `json:"vote_type"`
	BlockHash        sql.NullString `json:"block_hash"`
	Signature        sql.NullString `json:"signature"`
	Timestamp        sql.NullTime   `json:"timestamp"`
	CreatedAt        sql.NullTime   `json:"created_at"`
}
