// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	BatchCreateValidatorSnapshots(ctx context.Context, arg BatchCreateValidatorSnapshotsParams) error
	CreateConsensusEvent(ctx context.Context, arg CreateConsensusEventParams) (ConsensusEvent, error)
	CreateHeight(ctx context.Context, arg CreateHeightParams) (Height, error)
	CreateRound(ctx context.Context, arg CreateRoundParams) (Round, error)
	CreateValidator(ctx context.Context, arg CreateValidatorParams) (Validator, error)
	CreateValidatorSnapshot(ctx context.Context, arg CreateValidatorSnapshotParams) (ValidatorSnapshot, error)
	CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error)
	DeleteConsensusEventsOlderThan(ctx context.Context, height int64) error
	DeleteHeightsOlderThan(ctx context.Context, height int64) error
	DeleteRoundsOlderThan(ctx context.Context, height int64) error
	DeleteValidator(ctx context.Context, address string) error
	DeleteValidatorSnapshotsOlderThan(ctx context.Context, height int64) error
	DeleteVotesOlderThan(ctx context.Context, height int64) error
	GetConsensusEvent(ctx context.Context, id int64) (ConsensusEvent, error)
	GetConsensusEventsByType(ctx context.Context, arg GetConsensusEventsByTypeParams) ([]ConsensusEvent, error)
	GetConsensusEventsForHeight(ctx context.Context, height int64) ([]ConsensusEvent, error)
	GetConsensusEventsForRound(ctx context.Context, arg GetConsensusEventsForRoundParams) ([]ConsensusEvent, error)
	GetHeight(ctx context.Context, height int64) (Height, error)
	GetHeights(ctx context.Context, limit int64) ([]Height, error)
	GetLatestHeight(ctx context.Context) (Height, error)
	GetRecentConsensusEvents(ctx context.Context, limit int64) ([]ConsensusEvent, error)
	GetRecentRounds(ctx context.Context, limit int64) ([]Round, error)
	GetRound(ctx context.Context, arg GetRoundParams) (Round, error)
	GetRoundsForHeight(ctx context.Context, height int64) ([]Round, error)
	GetRoundsInRange(ctx context.Context, arg GetRoundsInRangeParams) ([]Round, error)
	GetValidator(ctx context.Context, address string) (Validator, error)
	GetValidatorSnapshot(ctx context.Context, arg GetValidatorSnapshotParams) (ValidatorSnapshot, error)
	GetValidatorSnapshotsForHeight(ctx context.Context, height int64) ([]ValidatorSnapshot, error)
	GetValidatorSnapshotsForValidator(ctx context.Context, arg GetValidatorSnapshotsForValidatorParams) ([]ValidatorSnapshot, error)
	GetValidators(ctx context.Context) ([]Validator, error)
	GetValidatorsByHeight(ctx context.Context, height int64) ([]GetValidatorsByHeightRow, error)
	GetVote(ctx context.Context, arg GetVoteParams) (Vote, error)
	GetVotesByType(ctx context.Context, arg GetVotesByTypeParams) ([]Vote, error)
	GetVotesForHeight(ctx context.Context, height int64) ([]Vote, error)
	GetVotesForRound(ctx context.Context, arg GetVotesForRoundParams) ([]Vote, error)
	GetVotesForValidator(ctx context.Context, arg GetVotesForValidatorParams) ([]Vote, error)
	GetVotingPowerForRound(ctx context.Context, arg GetVotingPowerForRoundParams) (GetVotingPowerForRoundRow, error)
	UpdateRoundStep(ctx context.Context, arg UpdateRoundStepParams) (Round, error)
	UpdateValidator(ctx context.Context, arg UpdateValidatorParams) (Validator, error)
	UpsertHeight(ctx context.Context, arg UpsertHeightParams) (Height, error)
	UpsertRound(ctx context.Context, arg UpsertRoundParams) (Round, error)
	UpsertValidator(ctx context.Context, arg UpsertValidatorParams) (Validator, error)
	UpsertValidatorSnapshot(ctx context.Context, arg UpsertValidatorSnapshotParams) (ValidatorSnapshot, error)
	UpsertVote(ctx context.Context, arg UpsertVoteParams) (Vote, error)
}

var _ Querier = (*Queries)(nil)
