// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: validators.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createValidator = `-- name: CreateValidator :one
INSERT INTO validators (operator_address, hex_address, public_key, voting_power, moniker)
VALUES (?, ?, ?, ?, ?)
RETURNING id, operator_address, hex_address, public_key, voting_power, moniker, created_at, updated_at
`

type CreateValidatorParams struct {
	OperatorAddress string         `json:"operator_address"`
	HexAddress      string         `json:"hex_address"`
	PublicKey       string         `json:"public_key"`
	VotingPower     int64          `json:"voting_power"`
	Moniker         sql.NullString `json:"moniker"`
}

func (q *Queries) CreateValidator(ctx context.Context, arg CreateValidatorParams) (Validator, error) {
	row := q.queryRow(ctx, q.createValidatorStmt, createValidator,
		arg.OperatorAddress,
		arg.HexAddress,
		arg.PublicKey,
		arg.VotingPower,
		arg.Moniker,
	)
	var i Validator
	err := row.Scan(
		&i.ID,
		&i.OperatorAddress,
		&i.HexAddress,
		&i.PublicKey,
		&i.VotingPower,
		&i.Moniker,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteValidator = `-- name: DeleteValidator :exec
DELETE FROM validators WHERE hex_address = ?
`

func (q *Queries) DeleteValidator(ctx context.Context, hexAddress string) error {
	_, err := q.exec(ctx, q.deleteValidatorStmt, deleteValidator, hexAddress)
	return err
}

const getValidator = `-- name: GetValidator :one
SELECT id, operator_address, hex_address, public_key, voting_power, moniker, created_at, updated_at FROM validators WHERE  hex_address = ? LIMIT 1
`

func (q *Queries) GetValidator(ctx context.Context, hexAddress string) (Validator, error) {
	row := q.queryRow(ctx, q.getValidatorStmt, getValidator, hexAddress)
	var i Validator
	err := row.Scan(
		&i.ID,
		&i.OperatorAddress,
		&i.HexAddress,
		&i.PublicKey,
		&i.VotingPower,
		&i.Moniker,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidators = `-- name: GetValidators :many
SELECT id, operator_address, hex_address, public_key, voting_power, moniker, created_at, updated_at FROM validators ORDER BY voting_power DESC
`

func (q *Queries) GetValidators(ctx context.Context) ([]Validator, error) {
	rows, err := q.query(ctx, q.getValidatorsStmt, getValidators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Validator{}
	for rows.Next() {
		var i Validator
		if err := rows.Scan(
			&i.ID,
			&i.OperatorAddress,
			&i.HexAddress,
			&i.PublicKey,
			&i.VotingPower,
			&i.Moniker,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidatorsByHeight = `-- name: GetValidatorsByHeight :many
SELECT v.id, v.operator_address, v.hex_address, v.public_key, v.voting_power, v.moniker, v.created_at, v.updated_at, vs.voting_power, vs.voting_power_percent, vs.is_proposer
FROM validators v
JOIN validator_snapshots vs ON v.hex_address = vs.validator_hex_address
WHERE vs.height = ?
ORDER BY vs.voting_power DESC
`

type GetValidatorsByHeightRow struct {
	ID                 int64           `json:"id"`
	OperatorAddress    string          `json:"operator_address"`
	HexAddress         string          `json:"hex_address"`
	PublicKey          string          `json:"public_key"`
	VotingPower        int64           `json:"voting_power"`
	Moniker            sql.NullString  `json:"moniker"`
	CreatedAt          sql.NullTime    `json:"created_at"`
	UpdatedAt          sql.NullTime    `json:"updated_at"`
	VotingPower_2      int64           `json:"voting_power_2"`
	VotingPowerPercent sql.NullFloat64 `json:"voting_power_percent"`
	IsProposer         sql.NullBool    `json:"is_proposer"`
}

func (q *Queries) GetValidatorsByHeight(ctx context.Context, height int64) ([]GetValidatorsByHeightRow, error) {
	rows, err := q.query(ctx, q.getValidatorsByHeightStmt, getValidatorsByHeight, height)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetValidatorsByHeightRow{}
	for rows.Next() {
		var i GetValidatorsByHeightRow
		if err := rows.Scan(
			&i.ID,
			&i.OperatorAddress,
			&i.HexAddress,
			&i.PublicKey,
			&i.VotingPower,
			&i.Moniker,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VotingPower_2,
			&i.VotingPowerPercent,
			&i.IsProposer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateValidator = `-- name: UpdateValidator :one
UPDATE validators 
SET operator_address = ?, public_key = ?, voting_power = ?, moniker = ?, updated_at = CURRENT_TIMESTAMP
WHERE hex_address = ?
RETURNING id, operator_address, hex_address, public_key, voting_power, moniker, created_at, updated_at
`

type UpdateValidatorParams struct {
	OperatorAddress string         `json:"operator_address"`
	PublicKey       string         `json:"public_key"`
	VotingPower     int64          `json:"voting_power"`
	Moniker         sql.NullString `json:"moniker"`
	HexAddress      string         `json:"hex_address"`
}

func (q *Queries) UpdateValidator(ctx context.Context, arg UpdateValidatorParams) (Validator, error) {
	row := q.queryRow(ctx, q.updateValidatorStmt, updateValidator,
		arg.OperatorAddress,
		arg.PublicKey,
		arg.VotingPower,
		arg.Moniker,
		arg.HexAddress,
	)
	var i Validator
	err := row.Scan(
		&i.ID,
		&i.OperatorAddress,
		&i.HexAddress,
		&i.PublicKey,
		&i.VotingPower,
		&i.Moniker,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertValidator = `-- name: UpsertValidator :one
INSERT INTO validators (operator_address, hex_address, public_key, voting_power, moniker)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(hex_address) DO UPDATE SET
    operator_address = excluded.operator_address,
    public_key = excluded.public_key,
    voting_power = excluded.voting_power,
    moniker = excluded.moniker,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, operator_address, hex_address, public_key, voting_power, moniker, created_at, updated_at
`

type UpsertValidatorParams struct {
	OperatorAddress string         `json:"operator_address"`
	HexAddress      string         `json:"hex_address"`
	PublicKey       string         `json:"public_key"`
	VotingPower     int64          `json:"voting_power"`
	Moniker         sql.NullString `json:"moniker"`
}

func (q *Queries) UpsertValidator(ctx context.Context, arg UpsertValidatorParams) (Validator, error) {
	row := q.queryRow(ctx, q.upsertValidatorStmt, upsertValidator,
		arg.OperatorAddress,
		arg.HexAddress,
		arg.PublicKey,
		arg.VotingPower,
		arg.Moniker,
	)
	var i Validator
	err := row.Scan(
		&i.ID,
		&i.OperatorAddress,
		&i.HexAddress,
		&i.PublicKey,
		&i.VotingPower,
		&i.Moniker,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
