// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	types0 "main/pkg/types"

	"github.com/cometbft/cometbft/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConsensusStorer creates a new instance of MockConsensusStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsensusStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsensusStorer {
	mock := &MockConsensusStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConsensusStorer is an autogenerated mock type for the ConsensusStorer type
type MockConsensusStorer struct {
	mock.Mock
}

type MockConsensusStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsensusStorer) EXPECT() *MockConsensusStorer_Expecter {
	return &MockConsensusStorer_Expecter{mock: &_m.Mock}
}

// CleanupOldData provides a mock function for the type MockConsensusStorer
func (_mock *MockConsensusStorer) CleanupOldData(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanupOldData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConsensusStorer_CleanupOldData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupOldData'
type MockConsensusStorer_CleanupOldData_Call struct {
	*mock.Call
}

// CleanupOldData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConsensusStorer_Expecter) CleanupOldData(ctx interface{}) *MockConsensusStorer_CleanupOldData_Call {
	return &MockConsensusStorer_CleanupOldData_Call{Call: _e.mock.On("CleanupOldData", ctx)}
}

func (_c *MockConsensusStorer_CleanupOldData_Call) Run(run func(ctx context.Context)) *MockConsensusStorer_CleanupOldData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConsensusStorer_CleanupOldData_Call) Return(err error) *MockConsensusStorer_CleanupOldData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConsensusStorer_CleanupOldData_Call) RunAndReturn(run func(ctx context.Context) error) *MockConsensusStorer_CleanupOldData_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockConsensusStorer
func (_mock *MockConsensusStorer) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConsensusStorer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockConsensusStorer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockConsensusStorer_Expecter) Close() *MockConsensusStorer_Close_Call {
	return &MockConsensusStorer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockConsensusStorer_Close_Call) Run(run func()) *MockConsensusStorer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConsensusStorer_Close_Call) Return(err error) *MockConsensusStorer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConsensusStorer_Close_Call) RunAndReturn(run func() error) *MockConsensusStorer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// StoreCometBFTEvents provides a mock function for the type MockConsensusStorer
func (_mock *MockConsensusStorer) StoreCometBFTEvents(ctx context.Context, events []types.TMEventData, validators types0.TMValidators) error {
	ret := _mock.Called(ctx, events, validators)

	if len(ret) == 0 {
		panic("no return value specified for StoreCometBFTEvents")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []types.TMEventData, types0.TMValidators) error); ok {
		r0 = returnFunc(ctx, events, validators)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConsensusStorer_StoreCometBFTEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreCometBFTEvents'
type MockConsensusStorer_StoreCometBFTEvents_Call struct {
	*mock.Call
}

// StoreCometBFTEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - events []types.TMEventData
//   - validators types0.TMValidators
func (_e *MockConsensusStorer_Expecter) StoreCometBFTEvents(ctx interface{}, events interface{}, validators interface{}) *MockConsensusStorer_StoreCometBFTEvents_Call {
	return &MockConsensusStorer_StoreCometBFTEvents_Call{Call: _e.mock.On("StoreCometBFTEvents", ctx, events, validators)}
}

func (_c *MockConsensusStorer_StoreCometBFTEvents_Call) Run(run func(ctx context.Context, events []types.TMEventData, validators types0.TMValidators)) *MockConsensusStorer_StoreCometBFTEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []types.TMEventData
		if args[1] != nil {
			arg1 = args[1].([]types.TMEventData)
		}
		var arg2 types0.TMValidators
		if args[2] != nil {
			arg2 = args[2].(types0.TMValidators)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConsensusStorer_StoreCometBFTEvents_Call) Return(err error) *MockConsensusStorer_StoreCometBFTEvents_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConsensusStorer_StoreCometBFTEvents_Call) RunAndReturn(run func(ctx context.Context, events []types.TMEventData, validators types0.TMValidators) error) *MockConsensusStorer_StoreCometBFTEvents_Call {
	_c.Call.Return(run)
	return _c
}

// StoreRoundData provides a mock function for the type MockConsensusStorer
func (_mock *MockConsensusStorer) StoreRoundData(ctx context.Context, height int64, round int32, data *types0.RoundData, validators types0.TMValidators) error {
	ret := _mock.Called(ctx, height, round, data, validators)

	if len(ret) == 0 {
		panic("no return value specified for StoreRoundData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int32, *types0.RoundData, types0.TMValidators) error); ok {
		r0 = returnFunc(ctx, height, round, data, validators)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConsensusStorer_StoreRoundData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreRoundData'
type MockConsensusStorer_StoreRoundData_Call struct {
	*mock.Call
}

// StoreRoundData is a helper method to define mock.On call
//   - ctx context.Context
//   - height int64
//   - round int32
//   - data *types0.RoundData
//   - validators types0.TMValidators
func (_e *MockConsensusStorer_Expecter) StoreRoundData(ctx interface{}, height interface{}, round interface{}, data interface{}, validators interface{}) *MockConsensusStorer_StoreRoundData_Call {
	return &MockConsensusStorer_StoreRoundData_Call{Call: _e.mock.On("StoreRoundData", ctx, height, round, data, validators)}
}

func (_c *MockConsensusStorer_StoreRoundData_Call) Run(run func(ctx context.Context, height int64, round int32, data *types0.RoundData, validators types0.TMValidators)) *MockConsensusStorer_StoreRoundData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 *types0.RoundData
		if args[3] != nil {
			arg3 = args[3].(*types0.RoundData)
		}
		var arg4 types0.TMValidators
		if args[4] != nil {
			arg4 = args[4].(types0.TMValidators)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockConsensusStorer_StoreRoundData_Call) Return(err error) *MockConsensusStorer_StoreRoundData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConsensusStorer_StoreRoundData_Call) RunAndReturn(run func(ctx context.Context, height int64, round int32, data *types0.RoundData, validators types0.TMValidators) error) *MockConsensusStorer_StoreRoundData_Call {
	_c.Call.Return(run)
	return _c
}

// StoreValidators provides a mock function for the type MockConsensusStorer
func (_mock *MockConsensusStorer) StoreValidators(ctx context.Context, height int64, validators types0.TMValidators) error {
	ret := _mock.Called(ctx, height, validators)

	if len(ret) == 0 {
		panic("no return value specified for StoreValidators")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, types0.TMValidators) error); ok {
		r0 = returnFunc(ctx, height, validators)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConsensusStorer_StoreValidators_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreValidators'
type MockConsensusStorer_StoreValidators_Call struct {
	*mock.Call
}

// StoreValidators is a helper method to define mock.On call
//   - ctx context.Context
//   - height int64
//   - validators types0.TMValidators
func (_e *MockConsensusStorer_Expecter) StoreValidators(ctx interface{}, height interface{}, validators interface{}) *MockConsensusStorer_StoreValidators_Call {
	return &MockConsensusStorer_StoreValidators_Call{Call: _e.mock.On("StoreValidators", ctx, height, validators)}
}

func (_c *MockConsensusStorer_StoreValidators_Call) Run(run func(ctx context.Context, height int64, validators types0.TMValidators)) *MockConsensusStorer_StoreValidators_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 types0.TMValidators
		if args[2] != nil {
			arg2 = args[2].(types0.TMValidators)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConsensusStorer_StoreValidators_Call) Return(err error) *MockConsensusStorer_StoreValidators_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConsensusStorer_StoreValidators_Call) RunAndReturn(run func(ctx context.Context, height int64, validators types0.TMValidators) error) *MockConsensusStorer_StoreValidators_Call {
	_c.Call.Return(run)
	return _c
}
